# this is a gnome file we use to enable autologin for the Bruger user. 
[daemon]
AutomaticLoginEnable=true
AutomaticLogin=bruger
AutomaticLoginUser=bruger

TimedLoginEnable=True
TimedLogin=bruger
TimedLoginDelay=10

# also this hides the user list in the login screen, so only the Bruger user is shown.
[greeter]
IncludeAll=false