# This is the variable we use to name the user.
# It's used in many scripts, and can be easily changed with Ansible if needed (WIP).
# If this file goes missing somehow, most scripts default to "Bruger"

GUEST_USER="HejHej"